### ISSUE TITLE
Chocolatey params not used on upgrade

### ISSUE THREAD

**Issue by bozho** [PowerShellOrg/cChoco#105]
`Set-TargetResource` is not passing `$chocoParams` to `Upgrade-Package` function.

Our use case is a problematic SQL Server Management Studio package, which lists a KB dependency, which makes choco install fail on Win10/Win2016. Therefore, we use `--ignore-dependencies` Chocolatey parameter. The parameter is ignored on upgrade, which makes upgrading SSMS tedious :-)

I will be submitting a pull request with a fix shortly.

**Comment by pauby** [comment]
Merged #106
