### ISSUE TITLE
cChocofeature module is missing in PowershellGallery hosted version

### ISSUE THREAD

**Issue by theonlydude1** [PowerShellOrg/cChoco#109]
Hello,
The module cChocoFeature is missing on the version hosted in the PowershellGallery:
![image](https://user-images.githubusercontent.com/18315609/40124229-66468314-5928-11e8-8603-ecaef6d4cfcb.png)
https://www.powershellgallery.com/packages/cChoco/2.3.1.0
Is it possible to add the missing folder and files in the published package ?
Thanks !

**Comment by Sebbl22** [comment]
I can confirm, that the cChocoFeature Resource is missing in the PSGallery version

**Comment by pauby** [comment]
cChocoFeature was added _after_ the last release was made. We're going to make another release shortly that will fix this.

**Comment by pauby** [comment]
New version was released in November 2018.
