### ISSUE TITLE
PowerShell Gallery version not up to date

### ISSUE THREAD

**Issue by sebastus** [PowerShellOrg/cChoco#11]
When will the PowerShell Gallery be updated with the latest?

**Comment by ferventcoder** [comment]
Who pushes this? @dlwyatt ? @smurawski ?

**Comment by dlwyatt** [comment]
Looks like Steve set it up, and he's the only owner listed at the moment:  http://www.powershellgallery.com/packages/cChoco/

**Comment by lawrencegripper** [comment]
@smurawski if you can share the key I'll look to setup an appveyor ci process to push up the version when new changes are merged in

Sound like a good plan?

**Comment by usepowershell** [comment]
@lawrencegripper what's your username for powershellgallery?  I'll add you as a maintainer.

**Comment by lawrencegripper** [comment]
lawrencegripper, same as here, should do the trick

**Comment by usepowershell** [comment]
@lawrencegripper Added to powershellgallery, you should have a notification from there - and after that, release at will

**Comment by lawrencegripper** [comment]
Thanks just setting up the CI build now to validate the DSC resources and push up to powershell gallery. @smurawski to setup the webhook so it kicks off after merging PRs/Changes I need to access the repo settings. Can you alter the permissions or add in the webhook for me?

I've emailed you the web hook, so go for whichever is easier.

**Comment by usepowershell** [comment]
@lawrencegripper I made you an admin on the repo, so let me know if that works for you.

**Comment by lawrencegripper** [comment]
Thanks that's perfect, have added the hook so now push should trigger quick test of the resource using xDSCResourceDesigner and publishing to PSGallery
