### ISSUE TITLE
Download artifacts from private proget using credentails

### ISSUE THREAD

**Issue by subash544772** [PowerShellOrg/cChoco#110]
Configuration BuildServerDSC     
{    
    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'    
    Import-DscResource -ModuleName cChoco
    $Cred = Get-AutomationPSCredential -Name "nugetcred"
             
    Node localhost            
    {       
       cChocoInstaller installChoco
      {
        InstallDir = "C:\Program Files (x86)\choco"
      }
cChocoPackageInstaller installaddproducttochangecontrol
      {
         Ensure = 'Present'
         Name = "AddProductToChangeControl"
         Source = "Private proget server"
         PsDscRunAsCredential = $Cred  
         DependsOn = "[cChocoInstaller]installChoco"
      }
    }
}  

what will be best way to download chocolatey artifacts from private proget feed?

**Comment by pauby** [comment]
@subash544772 That would be better of asked in the [cChoco Gitter channel](https://gitter.im/chocolatey/cchoco)
