### ISSUE TITLE
Add Required/Minimum/Maximum for Version

### ISSUE THREAD

**Issue by mrhockeymonkey** [PowerShellOrg/cChoco#117]
At work I currently use a forked version of this DSCResource that we have added to, One of these additions is to add some options for the case of a more recent version of a package being installed. In this instance we sometimes want to accept this higher version as okay. Much like the way Import-Module has parameters -Version, -RequiredVersion, -MinimumVersion and -MaximumVersion to give the user more control over their environment.

Example
```powershell
# will return as in desired state if any version greater to or equal than 1.2.3 is found
cChoco MyApp {
  Name= 'MyApp'
  MinimumVersion = '1.2.3'
}
```

If I get a PR put together would there be any appetite to merge in such a feature? The idea will be to add optional parameters and not affect the default behavior.

**Comment by pauby** [comment]
I this would be a useful enhancement. For those using it in anger it would be great to hear from them.

**Comment by ethanbergstrom** [comment]
I would note that this functionality is possible using the PackageManagement DSC resources, which when combined with the [Chocolatier package manager](https://www.powershellgallery.com/packages/Chocolatier/), provides the same result as what you're describing.

**Comment by mrhockeymonkey** [comment]
Good to know, I will have a play with Chocolatier when I can. I think its worth having this feature in the DSC resource too for completeness.
