### ISSUE TITLE
Clean up build and move to Chocolatey AppVeyor

### ISSUE THREAD

**Issue by pauby** [PowerShellOrg/cChoco#122]
Cleanup the build scripts (see #120 and #121) and move the build to the Chocolatey AppVeyor account.

**Comment by pauby** [comment]
@lawrencegripper Can you remove the build webhook from your AppVeyor account?

**Comment by lawrencegripper** [comment]
Sure - I've deleted the appveyor build now

**Comment by pauby** [comment]
Thanks @lawrencegripper

**Comment by pauby** [comment]
Build added into Chocolatey AppVeyor and PR #409 ran against it.
