### ISSUE TITLE
Add --no-progress feature

### ISSUE THREAD

**Issue by ksaffarian** [PowerShellOrg/cChoco#138]
Hi
cChoco is probably is used heavily in CI/CD pipelines to bootstrap servers.
The default settings in Choco is to show alot of progress, like download percentage and more stuff, which is a bit annoying when you want to review deployment logs.
I suggest you add the option to PackageInstaller resource to turn on/off verbose and progress logging.
Thanks for the nice work.
Cheers

**Comment by pauby** [comment]
This has already been completed and will be released in the next version.

Marking as a duplicate of #83
