### ISSUE TITLE
Install Chocolatey from an internal source

### ISSUE THREAD

**Issue by wizarden1** [PowerShellOrg/cChoco#139]
Hello,

I rewrite two resources and want to share with everyone.
1. Choco install.
Old Version based on script and require web server for install that not very useful for corporate(mass) deployment. And process looks like this:
cChoco resource > download install.ps1 > download zip with choco > extract zip > run script which install choco
My rebuilt resource
cChoco resource > request last(specific) version from nuget server (choco/nexus/...) > download nuget package > extract zip > run script which install choco
Pros:
- Do not require web server for choco
- do not use install.ps1
- add configurable random timeout in case mass deployment and error 529
- can be used with nuget proxies
Cons:
- not very universal, in some changes of install procedure will be necessary to rewrite resource

If this interested by some one, I will put code here

**Comment by pauby** [comment]
Downloading the install.ps1 doesn't require a web server. a Nexus repository with a RAW repo can store, and allow downloads, of it. As all of those components would also be interalised you would have a fully internalised version of Chocolatey to work with.

It sounds like your solution is very environment specific.

**Comment by wizarden1** [comment]
Nope it's not environment specific, you can read code by yourself
[cChocoInstaller.zip](https://github.com/chocolatey/cChoco/files/4291191/cChocoInstaller.zip)

**Comment by wizarden1** [comment]
If I need to install simultaneously a lot of servers in a moment after load ballancer, for example >10 at the same time. Source of install.ps1 as site chocolate doesn't useful because of connection limitation. I have more than 10 connection from one ip and got ip ban. For that reason I have to move to another web server install.ps1. And choco.zip also. So I rewrite choco installer, by remove install.ps1 completely, and download not choco.zip but choco.nupkg from nuget package source. And this source can be choco server or intranet server.

**Comment by pauby** [comment]
I said previously that the install.ps1 doesn't require a web server. a Nexus repository with a RAW repo can store, and allow downloads, of it. As all of those components would also be internalised you would have a fully internalised version of Chocolatey to work with.

So there is a solution for what you're talking about.

**Comment by pauby** [comment]
PR #142 was closed as stale.
