### ISSUE TITLE
WARNING: An existing Chocolatey installation was detected. Installation will not continue.

### ISSUE THREAD

**Issue by edcarino2** [PowerShellOrg/cChoco#155]
I had installed Chocolatey and already executed choco to install multiple software. However, after a month, choco is not working anymore. When I type “choco”, it’s returning error “Failed to run. No application is associated with the specified file.”

I’ve deleted Chocolatey installer manually so I could install this software again. I’ve deleted c:\ProgramData\Chocolatey directory and Chocolatey footprints in Environment Variables, and rebooted my computer.

I installed Chocolatey by issuing the command below in PowerShell Admin mode:
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

Error message is being returned below:
WARNING: An existing Chocolatey installation was detected. Installation will not continue.
For security reasons, this script will not overwrite existing installations.

**Comment by pauby** [comment]
There was an [update to the Chocolatey install script](https://github.com/chocolatey/home/issues/3). It's also not clear if this is related to the cChoco module.
