### ISSUE TITLE
cChocoSource - PSCredential for Set-TargetResource passed to MOF as Plain Test

### ISSUE THREAD

**Issue by ryanrichter94** [PowerShellOrg/cChoco#159]
Currently when setting up an authenticated source using cChocoSource. The PSCredential that gets passed using the Set-TargetResource function is written to the MOF file in plain text. 

Is their a way to obfuscate the source username and password within the MOF file instead of it getting written plain text? 

Looking at Microsoft documentation for DSC it looks like you can secure the MOF file with a certificate upon further researching. [link to docs on this](https://docs.microsoft.com/en-us/powershell/scripting/dsc/pull-server/securemof?view=powershell-5.1)

**Comment by pauby** [comment]
I appreciate this was some time ago, but I'm a little confused by this one. Encrypting the MOF would be done on your end node and not by this module. If you are using a pull configuration, then you would have to set up certificates to encrypt the MOF.

Can you elaborate on this one any further?

**Comment by ryanrichter94** [comment]
Hey @pauby apologies. Looking at this with some fresh eyes. You are correct that this would need to be a configuration made by an individual user to cert encrypt their MOF file. I'll go ahead and close off this issue.
