### ISSUE TITLE
cChocoInstaller - Files from a previous installation of Chocolatey were found

### ISSUE THREAD

**Issue by mivica** [PowerShellOrg/cChoco#162]
I get the below error intermittently with the "c:\choco" folder containing only one folder called "bin" and no files at all, e.g. "c:\choco\bin". The workaround is to remove the "c:\choco" folder from the drive, and the next DSC run goes all green. Can someone shed any light on this?

**[[cChocoInstaller]InstallChoco] Files from a previous installation of Chocolatey were found at 'c:\choco'.**

**Comment by pauby** [comment]
Can you provide the code you are using to install Choco / Package that results in this?

**Comment by mivica** [comment]
Please find attached.

[app.zip](https://github.com/chocolatey/cChoco/files/7294915/app.zip)

**Comment by pauby** [comment]
Does [this issue](https://github.com/chocolatey/cChoco/issues/155) resolve it?

**Comment by mivica** [comment]
The short answer is no. But at least we know what the issue may be, https://github.com/chocolatey/cChoco/issues/151#issuecomment-775166994. Is this going to get fixed and released soon?

**Comment by pauby** [comment]
This was fixed [here](https://github.com/chocolatey/cChoco/commit/fbb7835ab44e555a23256126074a59ac09a31777) and [released.](https://github.com/chocolatey/cChoco/releases/tag/v2.5.0) Are you running the latest version?

**Comment by mivica** [comment]
Yes, we are running the latest version, 2.5.0.
________________________________

**Comment by pauby** [comment]
Then you have a different issue.

You mention that you have a folder with `bin` in there? Can you run the normal Chocolatey install script (ie. without DSC), installing to `c:\choco`, while the `c:\chcoo\bin` folder exists?

**Comment by mivica** [comment]
The folder structure, including bin, is entirely created by cChoco install DSC, and still, it fails intermittently. I did not try to run it any other way than through DSC.

Did the file I shared helped in any way?

**Comment by pauby** [comment]
The folder structure isn't created by cChoco. It's created by the Chocolatey install script. 

Can you run the install script, on it's own, as I [requested above](https://github.com/chocolatey/cChoco/issues/162#issuecomment-936682647), to see if you get the same issues?

The file you shared didn't shed any more light on it.

**Comment by mivica** [comment]
Technically it is created by cChoco DSC module, namely by cChocoInstaller resource. How do I run normal Chocolatey install script?

**Comment by mivica** [comment]
Hi, the issue is that the actual download is failing with "(429) Too Many Requests.", see below. At the same time, the install directory has already been created [here ](https://github.com/chocolatey/cChoco/blob/a7247220d57f5c6f6cc043f6198d002a816989d1/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L183)before the [download](https://github.com/chocolatey/cChoco/blob/a7247220d57f5c6f6cc043f6198d002a816989d1/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L196) was triggered.  So the next time DSC runs and completes the download, Choco installer figures it is already installed due to the existing install folder and throws the error I raised initially. 

Is there a need to explicitly create this folder, does the installer creates it?
One way to fix this would be to move directory creation after the download was successful.

**"This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on cChocoInstaller DSC resource. FullyQualifiedErrorId is WebException. Error Message is Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429) Too Many Requests."."**

**Comment by pauby** [comment]
I'm not entirely sure what's going on in this. From my tests with just this code:

```
Configuration InstallChoco
{
    Import-DscResource -Module cChoco
    Node "localhost"
    {
        cChocoInstaller InstallChoco
        {
            InstallDir = "c:\choco"
        }
    }
}

$config = InstallChoco

Start-DscConfiguration -Path $config.psparentpath -Wait -Verbose -Force
```

Chocolatey is installed into `c:\choco` (as I'm not getting the error you get obviously). But, _there is no bin directory created_. The `bin` directory is used for shims that are created when packages are installed.

I also used this code from [this example](https://github.com/chocolatey/cChoco/blob/development/Examples/cChocoInstaller_cChocoInstallerExample.ps1) but I altered this [line](https://github.com/chocolatey/cChoco/blob/a7247220d57f5c6f6cc043f6198d002a816989d1/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L176) to read `$ChocoInstallScriptUrl = 'https://chocolatey.org/install.ps11'` (note the additional 1 on the end). This simulates the script not downloading (as the URL is incorrect). I get the following error:

```
VERBOSE: [5AF69F8C-D72B-4]:                            [[cChocoInstaller]InstallChoco] Downloading                      https://chocolatey.org/install.ps11 to C:\Windows\TEMP\532a435a-551e-4e0a-b996-1a544ad719d5\install.ps1
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
              + CategoryInfo          : NotSpecified: (:) [], CimException                                                            
              + FullyQualifiedErrorId : WebException                                                                                  
              + PSComputerName        : localhost                             
```

When I look at the `c:\choco` folder after the failed install, I see this:

![image](https://user-images.githubusercontent.com/12760779/137604073-2e560cc0-044e-4a83-8b5d-312a245b780c.png)

Note the `c:\choco` folder is created but no `bin` folder.

The issue you are having is not that cChoco [creates](https://github.com/chocolatey/cChoco/blob/a7247220d57f5c6f6cc043f6198d002a816989d1/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L183) the `c:\choco` folder. The issue you are having is that `c:\choco\bin` is being created and I'm not sure what that is. But as far as I can tell it's not cChoco.

cChoco runs the [Chocolatey install script](https://community.chocolatey.org/install.ps1) and it doesn't look for the install folder (ie. `c:\choco`), it looks for anything _inside_ the install folder and fails the install if it's found. As you have the `bin` folder in there Chocolatey won't install (see the `function Test-ChocolateyInstalled` in the [install script](https://community.chocolatey.org/install.ps1)).

So while cChoco is creating the [`c:\choco`](https://github.com/chocolatey/cChoco/blob/a7247220d57f5c6f6cc043f6198d002a816989d1/DSCResources/cChocoInstaller/cChocoInstaller.psm1#L183) folder (and I'm not entirely sure why) this doesn't appear to be your issue.

**Comment by mivica** [comment]
Hi Paul, thank you for your response and your time. Yes, you are correct; my initial assessment was incomplete. There is more than one download in this workflow, install.ps1 itself triggers at least one. They can all intermittently fail with HTTP 429 at different stages, which explains the bin folder.  429 error is documented on the Chocolatey [page](https://docs.chocolatey.org/en-us/community-repository/community-packages-disclaimer#rate-limiting). It makes it an unreliable approach to our automation scenario, which is why we decided to move away from Chocolatey entirely. I am closing this issue now.

**Comment by pauby** [comment]
@mivica you can host the install script yourself and pass the location of that to cChoco?

The Chocolatey Community Repository is not recommended for organisational use. There are a lot of docs around that (that I can't link to as I'm on my phone and don't have them to hand).

**Comment by mivica** [comment]
You can, and I tried. But one can still get 429 from the additional downloads the script itself is executing.
________________________________
