### ISSUE TITLE
Chocolatey install dwgtrueview rebooted my computer without asking

### ISSUE THREAD

**Issue by KrzaQ** [PowerShellOrg/cChoco#164]
**Describe the bug**
I ran `choco install -y dwgtrueview` and it (attempted to) reboot my PC after one of the bunch of KB installs.

**To Reproduce**
1. Have fully updated Windows 10 PRO
2. `choco install -y dwgtrueview`

**Expected behavior**
Software installs or does not, but does not close any other process.

**Screenshots**
![](https://i.imgur.com/kgmwHkO.png)

**Software (please complete the following information):**
 - OS: Windows 10 21H2 build 19044.1620
 - PowerShell Version 5.1.19041.1620

**Additional context**
I found it weird that it attempted to install Windows Server 2012 KB's.
Running the command again *without restarting the PC* (I was able to cancel) installed the program and it functions just fine.

**Comment by pauby** [comment]
This is an issue you would need to take up with the package maintainer. It doesn't sound like you are using the cChoco PowerShell DSC Resource so I'll go ahead and close this. We can always reopen it again if I'm wrong.

**Comment by KrzaQ** [comment]
Oh my, I am sorry, I thought this was chocolatey issues.

**Comment by pauby** [comment]
Chocolatey issues is over at https://github.com/chocolatey/choco/issues. However, this looks to be a package issue, not a Chocolatey one, so I'd start with the package maintainer.
