### ISSUE TITLE
Need an example to avoid corporate network rate limiting.

### ISSUE THREAD

**Issue by timothy-mcroy-cengage** [PowerShellOrg/cChoco#166]
**Is your feature request related to a problem? Please describe.**
The default Example.ps1 config does not include an example to utilize a private NuGet feed to install chocolatey. When folks use the default example, they will run into Chocolatey's HTTP 429 rate limiting if they create too many servers too quickly behind a NAT. 

**Describe the solution you'd like**
Introducing another example that demonstrates how to override the download location.

**Describe alternatives you've considered**
Possibly hosting a separate install.ps1 script in my local SCM. This isn't the right solution though as both are working around the same problem of DSC relying on external scripts that aren't part of the DSC module. An example of the workaround is more accessible and easier to implement.

**Additional context**
[Example implemented in a fork.](https://github.com/timothy-mcroy-cengage/cChoco/blob/development/Examples/cChocoInstaller_cChocoInstallerAlternateDownloadExample.ps1)

**Comment by pauby** [comment]
This was added [here](https://github.com/chocolatey/cChoco/commit/f85adebfd6bab767cbbb0f878a3a64bc29327457).
