### ISSUE TITLE
Why is cChocoInstaller.InstallDir required?

### ISSUE THREAD

**Issue by gambrose** [PowerShellOrg/cChoco#17]
Why is InstallDir required when Chocolatey installer has default value?

**Comment by ferventcoder** [comment]
No idea.

**Comment by ferventcoder** [comment]
I mean, I see this but I'm not a maintainer of cChoco so I'm not privy to how it was designed. It could be the chocolatey install directory, but I'm not sure.

**Comment by dlwyatt** [comment]
DSC resources require a key property of some sort; they can't exist without _something_ being mandatory.  I suspect that in this case, there just wasn't a better candidate.

**Comment by lawrencegripper** [comment]
@dlwyatt exactly my logic, it meets the key property constraint and felt like the best choice at the time. 

Happy to tweak if we can find a better candidate?

**Comment by dlwyatt** [comment]
IMO, it's not worth the breaking change even if you did find a "better" option later.  Works fine as-is.  :)

**Comment by gambrose** [comment]
That makes sense then.

I would propose version as a candidate with special handling for 'latest'. But as you say it would be a breaking change and not really worth it.

**Comment by trueqbit** [comment]
I know this is long closed, but how do I then determine chocolatey's default installdir from within a dsc config? I do want to keep the default.

**Comment by pauby** [comment]
`$env:ChocolateyInstall` ?

**Comment by trueqbit** [comment]
I presume `$env:ChocolateyInstall` doesn't exist *before* chocolatey is installed. I assume it should be `$env:ProgramData\chocolatey`?

**Comment by pauby** [comment]
@trueqbit That's correct.
