### ISSUE TITLE
Possibility to specify local packages in DSC config?

### ISSUE THREAD

**Issue by elliotwesoff** [PowerShellOrg/cChoco#18]
Hey Lawrence,

Thanks for all the hard work on this repo, we're really getting a lot of good use out of it in a program we're developing here at our firm.  I was just curious, though, if there's currently a way to specify local packages in the cChoco/DSC script so that it looks to a local package for installation rather than to the main Chocolatey package base?  Hope to hear from you soon, thanks!

-Elliot

**Comment by ferventcoder** [comment]
Definitely a necessity for business usage of Chocolatey

**Comment by ferventcoder** [comment]
And would bring it on par with the Puppet, Chef, Salt, and Ansible providers.

**Comment by lawrencegripper** [comment]
Hi @elliotwesoff,

Yeah I believe this is already present, if you specify the "Source" parameter on a package this will add an additional package source, like an internal or private nuget repository. 

https://github.com/PowerShellOrg/cChoco/blob/master/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L68

**Comment by elliotwesoff** [comment]
That worked beautifully!  Thank you @lawrencegripper
