### ISSUE TITLE
Review #512 https://github.com/chocolatey/choco/issues/512

### ISSUE THREAD

**Issue by lawrencegripper** [PowerShellOrg/cChoco#19]

**Comment by ferventcoder** [comment]
@lawrencegripper I created another issue. Feel free to update this one and close that as a duplicate or close this one as a duplicate. I wanted to provide folks an easier way to find the information as they are going to start seeing breakages today and need to know what to do for now while they wait for the provider to be fixed.

**Comment by ferventcoder** [comment]
Didn't this get implemented?

**Comment by lawrencegripper** [comment]
No this is likely related to #61 as the exit code returned from install isn't checked at all currently.

**Comment by ferventcoder** [comment]
Let's keep this open for a bit then.
