### ISSUE TITLE
Get-DscConfiguration Error

### ISSUE THREAD

**Issue by RichHopkins** [PowerShellOrg/cChoco#2]
I was able to use cChoco to deploy a Chocolatey package to my server.  I can run Test-DscConfiguration and it returns True, but when I run Get-DscConfiguration it errors out:

Get-DscConfiguration : The PowerShell provider C:\Program
Files\WindowsPowerShell\Modules\cChoco\DscResources\cChocoPackageInstall returned results that are not valid from
Get-TargetResource. The Ensure key is not a valid property in the corresponding provider schema file. The results from
Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the
corresponding provider schema file.
At line:1 char:1
- Get-DscConfiguration
- ~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidResult: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Ge
    t-DscConfiguration], CimException
  - FullyQualifiedErrorId : GetOperationResultInvalidResultFormat,Get-DscConfiguration

**Comment by lawrencegripper** [comment]
Great spot, should be all set, was a bug in the PackageInstaller resource that caused it to return an invalid configuration collection. Updated the powershell and mof so should be all set.

Wrote another example script here that might be useful for you too, it installs multiple packages from a list. https://gist.github.com/lawrencegripper/cee9b16f39db186e5f0b
