### ISSUE TITLE
Add cChocoConfig Resource

### ISSUE THREAD

**Issue by ramit-rulz** [PowerShellOrg/cChoco#20]
I have had some issues installing 32 bit Choco packages on 64 bit machines with SYSTEM user due to incorrect temp path resolution. 
There should be a way to configure cacheLocation in cChocoInstaller using DSC. Choco introduced this in v0.9.9.9 with "choco config set cacheLocation fullPath"
 https://github.com/chocolatey/choco/wiki/How-To-Change-Cache

**Comment by ferventcoder** [comment]
TBH - you've always been able to change the cache since like early 0.9.9.x series. The config command just made it easier to do.

**Comment by ramit-rulz** [comment]
Yes, you are right. So is there a way to define the cache location in cChocoInstaller DSC resource?

**Comment by ferventcoder** [comment]
I am not sure. I'm guessing not yet.

**Comment by lawrencegripper** [comment]
There isn't any provision for this in the cChocoInstaller. I'd be tempted to say this should be broken out into another Resource "cChocoConfiguration", for example. This can then be used to test, set and update the choco config independently of the installation, which would be a one time operation.

**Comment by ferventcoder** [comment]
I think this would be best served by a cChocoConfig resource. I'm going to rename this to that

**Comment by Outek** [comment]
Any news on this?
Is it possible to configure the cacheLocation?

**Comment by pauby** [comment]
@outek Inside cChoco, not yet. This issue is up for grabs. In the meantime see the [link posted above](https://github.com/chocolatey/choco/wiki/How-To-Change-Cache).
