### ISSUE TITLE
Add an 'Ensure' resource property

### ISSUE THREAD

**Issue by ebekker** [PowerShellOrg/cChoco#21]
Does it make sense to add an `Ensure` property (with value set `Present`, `Absent`) to mimic the structure of other DSC resources with similar behavior like the built-in `WindowsFeature` or add-on [`PackageManagementProviderResource`](https://github.com/PowerShell/PackageManagementProviderResource)?

This will allow prohibiting Choco packages via DSC.

**Comment by lawrencegripper** [comment]
Yeah would love to add this one in. I'd also considered, along the same lines, ensuring that the package is kept up to date with latest, if a specific version isn't specified. 

Not sure how much time I'll have to pick this up in the short term, happy to accept a pull request if you'd like to work on a rough implementation?

**Comment by ebekker** [comment]
I've submitted PR #22 with this enhancement, hopefully it's not too rough.  Note, I've only tested in on WMF 5.0 environment in a Pull-mode setup.

**Comment by javydekoning** [comment]
#22 was merged some time ago. Thus it seems that this issue has been resolved. Closing.
