### ISSUE TITLE
Add capability to  Runas for cChocoPackageInstall resource

### ISSUE THREAD

**Issue by erichexter** [PowerShellOrg/cChoco#23]
I have a situation when installing sql server express where once installed through the system user, there is no administrator (sysadmin) setup because the setup ran as system.  The only work around I can think of is to run the package installer inside of a Invoke-command script using psCredentials to invoke this in a user context. Then for this to work, I would need to pass in the credentials into the dsc script.  

If you were to agree with adding this capability, I am guessing the new execution code would need to be placed here: https://github.com/PowerShellOrg/cChoco/blob/master/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L144 

That will make that current code a little more squirrely.  it may be time to implement Splatting in that invocation block . https://technet.microsoft.com/en-us/magazine/gg675931.aspx 

Reference: here is some documentation on how one might pass credentials in the script as a parameter. 

https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-windows-extensions-dsc-credentials.md

**Comment by ferventcoder** [comment]
Is there nothing you can pass to the installer as far as an unattend file goes?

**Comment by ferventcoder** [comment]
Clarification/context - I'm assuming you are using DSC and Chocolatey with production level systems, so I'm under the impression you have your own repository of packages, thus have the ability to change the packaging for your sql server package. :)

**Comment by erichexter** [comment]
Actually this is for the build servers so I am using he public feeds. I
could create my own private feeds

On Friday, May 13, 2016, Rob Reynolds notifications@github.com wrote:

> Clarification/context - I'm assuming you are using DSC and Chocolatey with
> production level systems, so I'm assuming you have your own repository of
> packages, thus have the ability to change the packaging for your sql server
> package. :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/PowerShellOrg/cChoco/issues/23#issuecomment-219048596

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by ferventcoder** [comment]
Right on.

**Comment by javydekoning** [comment]
Can't you just use 'PsDscRunAsCredential'? You will need to set-up certificates and a pullserver to secure your credentials.
