### ISSUE TITLE
Test fails but Set doesn't configure Choco

### ISSUE THREAD

**Issue by javydekoning** [PowerShellOrg/cChoco#29]
Test fails because:
$InstallDir is not equal to $env:ChocolateyInstall

Set does not enter loop because: 
if (-not (DoesCommandExist choco) -or -not (IsChocoInstalled))

Command exists and Choco is installed. If Set is called, it should always set the configuration.

**Comment by DamianBis** [comment]
#32 has gone part way to fixing this.

Just needs another bit of code to uninstall chocolatey from incorrect location and install it in correct location
