### ISSUE TITLE
Looking for assistance with upkeep and improvements. 

### ISSUE THREAD

**Issue by lawrencegripper** [PowerShellOrg/cChoco#31]
Hi, 

When I created the resource I was regularly using DSC however, through a change of job and circumstances (baby on the way, joined a startup), I'm struggling to dedicate time to upkeep and improvements. 

I'm looking for community members who are using this resource and DSC more regularly than me, to take the resource forward. If that's you then drop me a note below or info[at]grippers.co.uk and we'll work out how best you can help out.

**Comment by ebekker** [comment]
Hey, I'm actually kinda in the opposite position wrt/ work -- we're trying to bring more DSC into our regular processes and automation, and we already make heavy use of choco to manage our server deployments (which led me to your DSC resource), so I would be willing to try to help and contribute.

**Comment by lawrencegripper** [comment]
Thanks for offering to help out, sounds like you'd be a great fit. 

Are you happy that we would aim to keep the resource useful on both desktop and server? 

One of the uses I still have for the module is building out a dev box with all the tools needed etc. 

If you're happy with that I'll sort out repo access for you. Have you used appveyor before? It's used at the moment  for the automated build and publish process to the powershellgallery

**Comment by ebekker** [comment]
Yes, I wouldn't want to do anything that would limit its utility unnecessarily -- actually I kinda misspoke in the sense that we do use it for _desktop-ish_ computers as well -- we're starting to use it to build out our developers' main work VMs which are hosted in the cloud so it's not just a server scenario in our case either.

**Comment by ebekker** [comment]
I use AV for some of my own OSS projects, for example [ACMESharp](https://github.com/ebekker/ACMESharp) uses [it](https://ci.appveyor.com/project/ebekker/acmesharp) for all automated builds and even kicking off [automated integration testing](https://build.powershell.org/externalStatus.html?projectId=ACMESharp) thanks to the free [Community Build service](https://powershell.org/community-build-server-is-live/) on PowerShell.org.

**Comment by MattHodge** [comment]
@lawrencegripper I would be interested too, was contemplating making my own class based resource for Choco or PRing this one. Just made a separate DSC resource here: https://github.com/MattHodge/Hubot-DSC-Resource

**Comment by lawrencegripper** [comment]
Thanks both, @MattHodge would be really happy to accept PRs. @ebekker I've invited you as a collaborator to the repo so you're all set to take it forward and hopefully it continues to be useful to others. Happy to get involved as and when I can, if you need me for anything just mention me in an issue and I'll keep an eye out for the notifications.

**Comment by javydekoning** [comment]
@lawrencegripper I created a few PR's, and would love to do some code clean-up to adhere to PSScriptAnalyzer rules and setup additional Pester tests. Let me know if and how I can get involved.

**Comment by lawrencegripper** [comment]
Massive thanks to @ebekker  and @javydekoning for the help - loads of progress over the last few months which is great to see! Closing this issue off for now.
