### ISSUE TITLE
cChocoInstaller Test-TargetResource returns false when chocolatey is installed

### ISSUE THREAD

**Issue by DamianBis** [PowerShellOrg/cChoco#32]
Issue is with how chocolatey is installed.

Line 65-68 does an Environment Variable for chocolatey install path. but it is only valid for that session. as soon as a new shell is opened the environment variable is gone.

**Comment by DamianBis** [comment]
Created a Pull Request with the change to make it work. have tested with v5

**Comment by lawrencegripper** [comment]
Thanks for the PR @DamianBis, I'm stuggling for time to support the project and @ebekker has kindly offered to take the helm. I'll leave this one with him to review.
