### ISSUE TITLE
shimgen fails to shims of chocolateypackage with PowershellDSC

### ISSUE THREAD

**Issue by lkjangir** [PowerShellOrg/cChoco#34]
I am installing NSSM using PowershellDSC. It installs NSSM but shimgen fails to generate a shim of nssm executable binary.  I am running DSC with administrator privileged account. 

Here is the error log - 

Calling command ['"C:\Choco\tools\shimgen.exe" --path="..\lib\NSSM\Tools\nssm-2.24\win64\nssm.exe" --output="C:\Choco\bin\nssm.exe"  --iconpath="C:\Choco\lib\NSSM\Tools\nssm-2.24\win64\nssm.exe"']
[DEBUG] -  [ShimGen] [WARN ] Could not extract icon from associated program. Using default. Error:
[DEBUG] -  [ShimGen]   Format not recognized by IconLib
[DEBUG] -  [ShimGen] Microsoft (R) Visual C# Compiler version 4.6.1055.0
[DEBUG] -  [ShimGen] for Microsoft (R) .NET Framework 4.5
[DEBUG] -  [ShimGen] Copyright (C) Microsoft Corporation. All rights reserved.
[DEBUG] -  [ShimGen] error CS0016: Could not write to output file 'c:\Choco\bin\nssm.exe' -- 'The directory name is invalid. '
[DEBUG] -  [ShimGen] [ERROR] ShimGen had an issue creating 'C:\Choco\bin\nssm.exe'. Please check the logs above.
[DEBUG] - Command ['"C:\Choco\tools\shimgen.exe" --path="..\lib\NSSM\Tools\nssm-2.24\win64\nssm.exe" --output="C:\Choco\bin\nssm.exe"  --iconpath="C:\Choco\lib\NSSM\Tools\nssm-2.24\win64\nssm.exe"'] exited with '1'

**Comment by ferventcoder** [comment]
This has been reported elsewhere as well.  

https://groups.google.com/d/msgid/chocolatey/4eb58e7b-ab61-4790-9f71-adbcfcb8dae4%40googlegroups.com

Same package. Out of curiosity, is that file locked and in use? `c:\Choco\bin\nssm.exe`

**Comment by ebekker** [comment]
Since this issue doesn't appear to be specific to the DSC resource for choco, I'm going to close this issue.

The discussion is continuing on the Google Group above, as well as in the comments section of the [package on chocolatey.org](https://chocolatey.org/packages/NSSM).

**Comment by ferventcoder** [comment]
@ebekker do you have a good email address I can reach out to? my email is ferventcoder at gmail. You can just send a message to that and I will follow up.

**Comment by coltaye** [comment]
Run
