### ISSUE TITLE
"Params" parameter not working

### ISSUE THREAD

**Issue by dcuomo** [PowerShellOrg/cChoco#38]
Not sure that this is a problem with the resource or if I'm doing something incorrectly, however I'm trying to maintain an offline, parameterized ADK 8.1 Installation.

Params in cChocoPackageInstaller contains
        **params = '/Features OptionID.WindowsPerformanceToolkit'**  

The package contains the following silentargs in the chocolateyinstall.ps1 
        **silentargs = "$env:ChocolateyInstallArguments /norestart /quiet /ceip off"**

The installation fails and exits with -2147023274.  

Manual installation of the adk works via the adk GUI
Chocolatey Installation of the package works with 
        **choco install adk81 --ia="/Features OptionID.WindowsPerformanceToolkit" -y**

Attempted to change the resource to use --ia instead of the default --params, same error.

is this an issue or am I passing the params in incorrectly?

**Comment by ferventcoder** [comment]
Do you have the underlying chocolatey log from the logs folder you can provide for the run?

**Comment by dcuomo** [comment]
[chocolatey.txt](https://github.com/PowerShellOrg/cChoco/files/394872/chocolatey.txt)

Thanks for taking a look.

From this line in the log -- _2016-08-01 18:12:53,123 [ERROR] - ERROR: Running ["c:\temp\ADK81\adksetup.exe" /Features OptionID.WindowsPerformanceToolkit /norestart /quiet /ceip off /Features OptionID.WindowsPerformanceToolkit] was not successful. Exit code was '-2147023274'_

It appears that it's appending the $env:chocolateyInstallArguments at the beginning and end of the line?

**Comment by ferventcoder** [comment]
Look at the arguments - 

`c:\temp\ADK81\adksetup.exe" /Features OptionID.WindowsPerformanceToolkit /norestart /quiet /ceip off /Features OptionID.WindowsPerformanceToolkit`

I see what is wrong now. Chocolatey Install Arguments are already passed transparently to the native installer, and require no interaction from the package itself.

Change:

``` powershell
silentArgs    = "$env:chocolateyInstallArguments /norestart /quiet /ceip off"
```

to

``` powershell
silentArgs    = "/norestart /quiet /ceip off"
```

**Comment by ferventcoder** [comment]
@lawrencegripper @ebekker please close as not an issue. Thanks. 👍

**Comment by ferventcoder** [comment]
@dcuomo apologies, misread what you wrote in your original post.

**Comment by dcuomo** [comment]
My larger question, which I didn't make clear and mis-titled the "issue" (and apologize for throwing the troubleshooting of course) is that I don't believe there is a way to pass parameters to the native installer unless I'm doing something incorrectly (kind of a newbie to chocolatey - so totally possible).  In context of the ADK, on one system I'd like to install the performance toolkit.  On another system, I'd like to install the preinstallation environment and deployment tools.  I'd prefer if I could use one package and pass in the parameters via the DSC Resource to a specific node.

I'm receiving the same error whether $env:ChocolateyInstallArguments is added to the silent args or not using the cChoco module in a DSC Configuration.
Exit code was '-2147023274'
Chocolatey Log shows ["c:\temp\ADK81\adksetup.exe" /norestart /quiet /ceip off ] was not successful. Exit code was '-2147023274'

As a side note, during my troubleshooting I had changed the DSC Resource from using the --params to --ia.  I accidentally forwarded the chocolatey log from that attempt last time. - Again, apologies...

For reference, running the following from the command line works perfectly (with $env:ChocolateyInstallArguments in the ChocolateyInstall.ps1 line)
choco install adk81 --ia="/Features OptionID.WindowsPerformanceToolkit"

However this (which is how the DSC Resource implements it) installs the entire ADK
choco install adk81 --params="/Features OptionID.WindowsPerformanceToolkit"

First - Is there a way to pass items to a native installer such that I can use one package through the DSC Configuration, or is that something I should try to help solve ;-)
Second - Why do I get different results when running chocolatey from the cmd line vs via the DSC Configuration?

**Comment by nebffa** [comment]
I second what @dcuomo is saying. It would be really useful to be able to pass install arguments to chocolatey

**Comment by ferventcoder** [comment]
> As a side note, during my troubleshooting I had changed the DSC Resource from using the --params to --ia. I accidentally forwarded the chocolatey log from that attempt last time. 

That makes a bunch more sense.

> First - Is there a way to pass items to a native installer such that I can use one package through the DSC Configuration, or is that something I should try to help solve ;-)

This seems to make sense as an add unless someone else has already added this (which it could be)

> Second - Why do I get different results when running chocolatey from the cmd line vs via the DSC Configuration?

The user context likely. When you run it, you are running it under your username. When DSC runs it, I believe it runs under LocalSystem (BUILTIN\SYSTEM). Not sure if that would cause any differences. I know that folks like @jpogran, @ebekker, and @lawrencegripper could probably provide more insight on the intricacies of DSC.

**Comment by javydekoning** [comment]
@dcuomo I don't have an answer to your first question. 

As for the second, what @ferventcoder mentions is correct. DSC runs under the 'nt authority\system' context UNLESS you specify 'PsDscRunAsCredential'. This results in the fact that some installers might behave differently or even fail completely. An example of this would be Atom package which doesn't install at all if no credentials are specified.

**Comment by 4c74356b41** [comment]
But why don't you want to add ability to pass install arguments?

**Comment by ferventcoder** [comment]
@4c74356b41 provided you are not a bot - we want both.

**Comment by 4c74356b41** [comment]
well, that's a nice way to talk to a stranger

**Comment by javydekoning** [comment]
@4c74356b41  we are working on that. Params is only to be used for Package params NOT chocolatey params. Refer to #52 for more details.

**Comment by 4c74356b41** [comment]
thanks, I got that already!

**Comment by ferventcoder** [comment]
> well, that's a nice way to talk to a stranger

@4c74356b41 Apologies, it's the username. It's similar to what we've seen in the past as bots (seemingly random characters for user name).

**Comment by 4c74356b41** [comment]
hah, never thought about that ;) its okay ;) ya, this name is a bit random, but I love it ;)

**Comment by lawrencegripper** [comment]
Closing this one off now as think we're sorted with the PR from @javydekoning
