### ISSUE TITLE
Question: is it possible to pass params to installation?

### ISSUE THREAD

**Issue by alkampfergit** [PowerShellOrg/cChoco#4]
Ex: when installing git.install we can choose some options like 

 -params '"/GitAndUnixToolsOnPath /NoAutoCrlf"'.

is it possible to specify params in DSC?

**Comment by lawrencegripper** [comment]
I've just pushed an update to add this in, can you have a go and see if it behaves as expected?

See the ExampleConfig.ps1 to see if being used.

**Comment by alkampfergit** [comment]
Thanks a lot, I'll check as soon as possible :).

## 

Gian Maria Ricci
Cell: +39 320 0136949

http://mvp.microsoft.com/en-us/mvp/Gian%20Maria%20Ricci-4025635
http://www.linkedin.com/in/gianmariaricci  https://twitter.com/alkampfer
  http://feeds.feedburner.com/AlkampferEng

**Comment by lawrencegripper** [comment]
Closing the loop on this one.
