### ISSUE TITLE
Upgrading Packages with DSC

### ISSUE THREAD

**Issue by priceflex** [PowerShellOrg/cChoco#42]
I have used the command: cup    before to update the packages and it works great for public hosted packages. We currently have a bunch of locally maintained packages and I wanted to know if there was a way to have DSC update the local and public packages automatically.

**Comment by priceflex** [comment]
Or Is there a way to just add the version number to the configuration?

**Comment by DamianBis** [comment]
Can do it like this

```
  cChocoPackageInstaller installAtomSpecificVersion
  {
    Name = "atom"
    Version = "0.155.0"
    DependsOn = "[cChocoInstaller]installChoco"
  }
```

#39  is open to allow "Latest" as a version number. this should be available in the next couple of weeks.

**Comment by priceflex** [comment]
Thank you I will try that.
