### ISSUE TITLE
Chocolatey 0.10 breaking some installers. 

### ISSUE THREAD

**Issue by javydekoning** [PowerShellOrg/cChoco#45]
0.10.0 includes a major security enhancement (checksum requirement). This breaks several packages right now and will hopefully be fixed by maintainers in the future. However the cChocoPackageInstaller resource requires an ability to set the --allow-empty-checksums param.

**Comment by OxHobbs** [comment]
I ran into this issue as well and have added an additional property that allows you to specify a property to bypass the checksum (--allowEmptyChecksums).  Added pull request to address the issue.

**Comment by ferventcoder** [comment]
I appreciate the way you stated this @javydekoning. Very nice. 

For other folks looking for more information, take a look at https://github.com/chocolatey/choco/issues/910

**Comment by javydekoning** [comment]
@FatherDragon Thanks, I also added a pull request with a slightly more dynamic approach to also allow other Choco Install Params as this feature is currently lacking. See PR #50 

@ferventcoder cool, thanks for including the reference. Very nice addition to Choco :)

**Comment by 4c74356b41** [comment]
Could you, perhaps enlighten me? Params = "--allow-empty-checksums" doesn't work.

Thanks!

**Comment by ferventcoder** [comment]
@4c74356b41 anything with `Params` goes into package parameters -  `choco install --package-parameters 'value of Params here'`

**Comment by 4c74356b41** [comment]
I'm talking about cchoco. when specifying Params = "--allow-empty-checksums" package fails, but when doing the same thing manually install succeeds

**Comment by lawrencegripper** [comment]
The params argument in cChoco maps to the "--package-parameters" argument on choco not as a parameter on the choco command. 

What your config will do, if I haven't missunderstood, is this..

choco install git --package-parameters '--allow-empty-checksums'

Where what you want is this...

choco install git --allow-empty-checksums

#52 is working on adding this functionality at the moment

**Comment by 4c74356b41** [comment]
So there's no way to install package with empty checksum using cchoco at the moment?
And no way to configure choco natively? 
choco feature enable -n allowEmptyChecksums? Without adding script resource to dsc configuration?

**Comment by lawrencegripper** [comment]
Correct, @javydekoning has kindly submitted a PR to fix this and is making some changes before we merge it in and push out an update.

**Comment by 4c74356b41** [comment]
hm, could you perhaps add ability to configure chocolatey: (and this could be, say, comma separated list?)

```
    cChocoInstaller installChoco
    {
        InstallDir = "c:\choco"
        DependsOn = "[File]ChocoDir"
        Params = "feature enable -n allowEmptyChecksums, feature enable -n allowGlobalConfirmation" 
    }
```

**Comment by lawrencegripper** [comment]
We're looking at enabling this on a per-package basis, for flexibility, rather than in cChocoInstaller. Happy to discuss allowing something in cChocoInstaller but best to start a seperate issue to talk through this now. 

If you'd like to look at what is being worked have a read of #52 I'm going to close off this issue for now though so we don't have two conversations running in parallel.

**Comment by ferventcoder** [comment]
For posterity sake, I added all of the different options you have when you run into this issue here: https://github.com/chocolatey/choco/issues/112#issue-58511395

The first option is consumer-based. Did you know you could pass the checksums yourself (once #52 is implemented of course)?

**Comment by 4c74356b41** [comment]
yeah, I figured that out, but atm cchoco doesn't support that.
seems that the only option now is to use script extension along with cchoco to install such packages.
