### ISSUE TITLE
Any plans to implement "source"?

### ISSUE THREAD

**Issue by sebastus** [PowerShellOrg/cChoco#5]
I'd like to put private packages out on MyGet, use cChoco to install them.

**Comment by lawrencegripper** [comment]
I haven't got plans to implement as I'm a bit backed up at the moment. Would be happy to give you some pointers on how to add it and accept a pull request, if you wanted to add the functionality?

**Comment by sebastus** [comment]
Continuous Deployment to a VM is the use case that I'm interested in developing.  Being able to source packages as needed is one requirement.  Turns out to be pretty simple without changing cChoco - just put a 'choco source' statement in the Configuration.

Another is being able to verify a particular version of a package and upgrade if necessary.  I might be willing to invest, and I would definitely take you up on your offer for pointers.  Step one is to ensure that all use cases are clearly understood so a level of effort can be estimated.  Any thoughts?

**Comment by sebastus** [comment]
Submitted a pull request for these two features.

**Comment by lawrencegripper** [comment]
Thanks for adding these in, I'm merged the pull request now.

 #9 

I'm not sure how some of the install scripts would handle rolling back versions, this may error, however for your Continuous deployments scenario I can't see this being a big issue.
