### ISSUE TITLE
Cannot find path 'C:\ProgramData\chocolatey\config' because it does not exist.

### ISSUE THREAD

**Issue by kcighon** [PowerShellOrg/cChoco#54]
Setting source with "cChocoSource" immediately after "cChocoInstaller" fails with 
"Cannot find path 'C:\ProgramData\chocolatey\config' because it does not exist." 

Confirmed Config folder does not exist until choco.exe is run for the first time.

Output from Start-DSCconfiguration:

VERBOSE: [SERVER1]: LCM:  [ Start  Resource ]  [[cChocoSource]setMYChocoSource]
VERBOSE: [SERVER1]: LCM:  [ Start  Test     ]  [[cChocoSource]setMYChocoSource]
VERBOSE: [SERVER1]:                            [[cChocoSource]setMYChocoSource] Start Test-TargetResource
Cannot find path 'C:\ProgramData\chocolatey\config' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\chocolatey\config:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
    + PSComputerName        : localhost

Cannot bind argument to parameter 'Path' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentC
   ommand
    + PSComputerName        : localhost

**Comment by ferventcoder** [comment]
For context - this is a known thing. 

For the Puppet provider, we run a small command to ensure that everything is set up:
https://github.com/puppetlabs/puppetlabs-chocolatey/blob/d03ba8d883e7564df7da0890f5df3e460de3ce66/lib/puppet_x/chocolatey/chocolatey_common.rb#L67

**Comment by javydekoning** [comment]
Regarding #54, I think it be better to run 'choco' once after the chocoinstaller 'set' function instead of running it in every  cChocoSource Test

**Comment by ferventcoder** [comment]
I agree with @javydekoning

**Comment by lawrencegripper** [comment]
Agree, PR looks good. I'll give it a spin tonight and merge it in - all being well. 

Thanks for the contribution @kcighon!

**Comment by javydekoning** [comment]
Latest master branch includes a fix. Thanks!
