### ISSUE TITLE
Migrate to Chocolatey GitHub namespace?

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#69]
### Discussion
Almost all config mgmt integration tools have a company or folks from that company that continue development on the Chocolatey integration. DSC is a bit different. It does not have that with things like cChoco. 

After seeing a few folks work on this and then not be able to continue development, I'm wondering if it is best if this should be moved up under Chocolatey management? I talked to @smurawski a couple of days ago about this but I want to get other folks opinions as well.

### Notes
* All folks that have a commit token, let's retain that.
* The Chocolatey team would need maintainership rights to the PowerShell gallery for this module.

**Comment by lawrencegripper** [comment]
I think this would be an excellent idea. 

I'd like to say a massive thank you to @javydekoning and @ebekker for their contributions and keeping the module up-to-date after I stepped back.

What are the next steps?
- Add @ferventcoder to contributors on github
- Add powershell gallery permissions for @ferventcoder too

**Comment by ebekker** [comment]
I agree this is a great idea.  I'm only sorry I wasn't able to contribute more.

**Comment by javydekoning** [comment]
@ferventcoder @smurawski, that might be a lot better. Unfortunately, priorities have shifted. I'm no longer actively using Chocolatey or DSC. Hopefully this change can bring the DSC resource back on track.

**Comment by usepowershell** [comment]
@ferventcoder @lawrencegripper I've sent Rob a link to join this repo as an admin, which should give him the ability to transfer it to the chocolatey org.

**Comment by usepowershell** [comment]
@ferventcoder what's your user id for powershell gallery?

**Comment by ferventcoder** [comment]
@smurawski ferventcoder (just registered)

**Comment by ferventcoder** [comment]
This has been migrated over to chocolatey/cChoco.

**Comment by ferventcoder** [comment]
I've added some folks to @chocolatey/powershelldsc - if I missed anyone let me know please. It was basically everyone that commented here I knew had commit rights.

**Comment by usepowershell** [comment]
@ferventcoder I've added you on powershellgallery as well.

**Comment by lawrencegripper** [comment]
Great, looks good. 

I setup an AppVeyor CI pipeline for the repo a while back which build the module and publishes to the powershell gallery when changes are made on master. It will also run against PR's (I think) and I believe @javydekoning  improved it and added some pester tests too. 

Would be good to give you permissions for it too @ferventcoder, do you have an account with appveyor I can add?

**Comment by javydekoning** [comment]
Yes, it will run against PR's. Obviously it will not publish to PS Gallery on PR's. Only on successful changes to Master it will publish. 

I indeed started building Pester tests, but only for the components I've changed.

**Comment by ferventcoder** [comment]
Would love to chat with someone to understand/document more on how this gets released.

**Comment by ferventcoder** [comment]
@lawrencegripper I do have an account with AppVeyor. It's my ferventcoder github account

**Comment by ferventcoder** [comment]
I have some very dumb questions regarding publish module - I want to see projectUrl to point back to here, and I want to add release notes. How does one add those things?

**Comment by ferventcoder** [comment]
@lawrencegripper @javydekoning going to attempt pushing an updated version. I don't have access to appveyor so wish me luck.

**Comment by ferventcoder** [comment]
I think this is ready to close.
