### ISSUE TITLE
Add an Apache v2 License to cChoco

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#70]
Howdy @chocolatey/powershelldsc  - What was the original intent for licensing here?

**Comment by ferventcoder** [comment]
I'd love to set an Apache v2 License on this code, however to move from no license to a license requires a thumbs up from contributors. 

For every person identified, you must create a comment on this issue so that the licensing can be added. The apache v2 license is super business friendly and can be found at https://www.apache.org/licenses/LICENSE-2.0.html (it's the same license that Chocolatey uses for all of its open source repositories).

* [x] @lawrencegripper 
* [x] @ebekker 
* [x] @ferventcoder
* [x] @mrpullen 
* [x] @javydekoning 
* [x] @RobFaie 
* [x] @kcighon 
* [x] @bozho 
* [x] @smurawski 
* [x] @dlwyatt 
* [x] @sebastus 
* [x] @absolutejam 
* [x] @bgelens 
* [x] @ptoonen 
* [x] @ITGuyOU 


If your name has been identified, please add a comment that says **"I agree with a move to Apache v2 licensing for my contributions to this repository."** A simple thumbs up will not be enough.

**Comment by ferventcoder** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by usepowershell** [comment]
I agree with the move to Apache v2 for licensing my contributions to this repository

**Comment by javydekoning** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by ptoonen** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by lawrencegripper** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository

**History**

When I first wrote the resource it was submitted to the powershellorg as a PR to a repo which grouped together lots of community dsc resources and already had a license. @smurawski pulled out the code and committed it to a new repo to make it easier to manage for me and likely that's when we missed the licensing going missing.

**Comment by bgelens** [comment]
I agree with the move to Apache v2 for licensing my contributions to this repository

**Comment by bozho** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by ferventcoder** [comment]
Still waiting on a few more, especially @ebekker, @mrpullen, and @RobFaie

**Comment by ferventcoder** [comment]
If we can't get all folks to sign off on this, we will need to rewrite the sections of code that were contributed so we can move forward with the licensing. I'm not keen on that, so hopefully folks are able to agree with the change.

**Comment by ebekker** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by ferventcoder** [comment]
Ping @mrpullen @RobFaie @kcighon @dlwyatt @sebastus @absolutejam

**Comment by dlwyatt** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by sebastus** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by ferventcoder** [comment]
And then there were four @mrpullen @RobFaie @kcighon @absolutejam. If anyone knows these folks, can you help me reach out to them?

**Comment by ferventcoder** [comment]
I sent an email to @absolutejam as that was listed in James' GitHub profile.

**Comment by mrpullen** [comment]
Mrpullen here.

I agree with a move to Apache v2 Licensing.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ferventcoder** [comment]
Ones we would not necessarily need to rewrite to change the licensing:

* https://github.com/chocolatey/cChoco/commits?author=kcighon (smaller, maint type commits)
* https://github.com/chocolatey/cChoco/commits?author=absolutejam (changing to single quotes, so also mostly maint)
* https://github.com/chocolatey/cChoco/commits?author=ITGuyOU (added version to example, so documentation type of commit)

However I would really like to get @RobFaie 's signoff - https://github.com/chocolatey/cChoco/commits?author=RobFaie

**Comment by ferventcoder** [comment]
@ITGuyOU your commit came after, but would you mind also responding here?

**Comment by ferventcoder** [comment]
@mrpullen Thank you!

**Comment by ferventcoder** [comment]
I may have found @RobFaie through [LinkedIn](https://www.linkedin.com/in/robert-w-mcleod/) and have reached out.

**Comment by absolutejam** [comment]
Sorry for the inconvenience, I saw this issue had  some activity but I didn't realising you were waiting for me! I think it's a great idea to move to the Apache 2 license.

'I agree with a move to Apache v2 licensing for my contributions to this repository.'

**Comment by ferventcoder** [comment]
@absolutejam thanks!

**Comment by RobFaie** [comment]
All good with me.

**Comment by ferventcoder** [comment]
@RobFaie thanks for that. Is there a chance you could provide the official wording requested?

**Comment by variableresistor** [comment]
I agree with the move to Apache v2 for licensing my contributions to this repository

**Comment by ferventcoder** [comment]
Thanks @ITGuyOU !

**Comment by variableresistor** [comment]
Sorry for the delay, @ferventcoder . I've been hunting for a new employer, which has kept me tied up.

**Comment by ferventcoder** [comment]
No worries sir, I did not include your name on this until recently.

**Comment by RobFaie** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by Jark** [comment]
I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by kcighon** [comment]
Apologies for delayed response - I agree with a move to Apache v2 licensing for my contributions to this repository.

**Comment by variableresistor** [comment]
I agree with a move to Apache v2 licensing for my contributions to this
repository.

**Comment by ferventcoder** [comment]
Apache v2 licensing has been applied. Thanks all!!
