### ISSUE TITLE
cChocoFeature Resource - Configure Chocolatey Features

### ISSUE THREAD

**Issue by ferventcoder** [PowerShellOrg/cChoco#71]
As a followup for #20, it would be great to configure features as well through the DSC resource.

**Comment by lukegriffith** [comment]
I have a forked version of this, I'll look to get a pull request together.

**Comment by lukegriffith** [comment]
Implemented in pull request https://github.com/chocolatey/cChoco/pull/89

**Comment by ferventcoder** [comment]
Thanks for your contribution!

**Comment by sergey-s-betke** [comment]
Please, release new version with cChocoFeature to repository!
