### ISSUE TITLE
cChocoSource 

### ISSUE THREAD

**Issue by johnm-woollies** [PowerShellOrg/cChoco#93]
it appears this code was a copy and paste of the cChocoInstallPackage resource. 

When attempting to add a source it tries to locate a nuget xml file which obviously it won't find as adding a source does not require this.

**Comment by pauby** [comment]
I know this is an old one - can't see anything in the code for this. Can you confirm this is still an issue and provide the relevant logs?

**Comment by pauby** [comment]
Going to go ahead and close this now. We can always reopen it later when we have more information.
