### ISSUE TITLE
multiple packages deployment

### ISSUE THREAD

**Issue by nkv16786** [PowerShellOrg/cChoco#97]
1).Is there a way to deploy multiple packages with a specific version of each package?

2). How to know what versions are available for a particular package

**Comment by ferventcoder** [comment]
1). You create a package resource for each. You also get to define version I believe.

2). You get to decide what versions you create. If you are using this for organizational use, please reconsider about using the community repository as we want your experience to be 100% reliable. Please read https://chocolatey.org/docs/community-packages-disclaimer

**Comment by ferventcoder** [comment]
If you do find you are being blocked/soft banned by Cloudflare, reach out through those instructions so we can help.

**Comment by ferventcoder** [comment]
Wrong comment on wrong issue, ignore.
